# EDCommon.framework
# GNUmakefile.preamble
#
# $Id: GNUmakefile.preamble,v 2.0 2002-08-16 18:12:43 erik Exp $


NAME = EDCommon
PATCH_HEADERS = EDCommon.h
VERS_FILE = $(NAME)_vers.c

EDCommon_C_FILES += $(VERS_FILE)
