# EDCommon.framework
# GNUmakefile.preamble
#
# $Id: GNUmakefile.preamble,v 1.1 2002-04-14 14:57:53 znek Exp $


NAME = EDCommon
PATCH_HEADERS = EDCommon.h
VERS_FILE = $(NAME)_vers.c

EDCommon_C_FILES += $(VERS_FILE)
