# EDCommon.framework
# GNUmakefile.preamble
#
# $Id: GNUmakefile.preamble,v 2.1 2003-11-08 20:04:45 znek Exp $


-include GNUmakefile.preamble.local

NAME = EDCommon
PATCH_HEADERS = EDCommon.h
VERS_FILE = $(NAME)_vers.c

EDCommon_C_FILES += $(VERS_FILE)
